#!/usr/bin/env node
/**
 * fetch-fonts.mjs — vendors the OFL typefaces locally so the game makes zero
 * external requests on GitHub Pages.
 *
 * Pulls the Google Fonts CSS with a modern UA (to get woff2), keeps only the
 * `latin` and `latin-ext` subsets (enough for EN + pt-BR plus accented names
 * like Wałęsa and Dvořák), downloads each file into assets/fonts/, and emits
 * css/fonts.css with relative URLs.
 *
 * Run once:  node tools/fetch-fonts.mjs
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const FONT_DIR = resolve(ROOT, 'assets/fonts');
const CSS_OUT = resolve(ROOT, 'css/fonts.css');

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const FAMILIES = [
  // [css2 query, local file slug, role comment]
  ['UnifrakturMaguntia', 'unifraktur', 'masthead blackletter'],
  ['Playfair+Display:ital,wght@0,400..900;1,400..900', 'playfair', 'headlines (Didone)'],
  ['EB+Garamond:ital,wght@0,400..800;1,400..800', 'garamond', 'body text'],
  ['IM+Fell+English:ital@0;1', 'imfell', 'antique subheads'],
  ['Special+Elite', 'elite', 'typewriter stamps'],
];

const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

async function get(url, asBuffer = false) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return asBuffer ? Buffer.from(await res.arrayBuffer()) : res.text();
}

/** Split the CSS into { subset, block } records using the `/* subset *\/` comments. */
function parseBlocks(css) {
  const out = [];
  const re = /\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
  let m;
  while ((m = re.exec(css))) out.push({ subset: m[1], block: m[2] });
  return out;
}

const field = (block, name) => {
  const m = block.match(new RegExp(`${name}:\\s*([^;]+);`));
  return m ? m[1].trim() : '';
};

mkdirSync(FONT_DIR, { recursive: true });
mkdirSync(dirname(CSS_OUT), { recursive: true });

const chunks = [
  '/* Generated by tools/fetch-fonts.mjs — do not edit by hand.',
  ' * All families are SIL Open Font License 1.1. See CREDITS.md.',
  ' */',
  '',
];
const manifest = [];
let total = 0;

for (const [query, slug, role] of FAMILIES) {
  const css = await get(`https://fonts.googleapis.com/css2?family=${query}&display=swap`);
  const blocks = parseBlocks(css).filter((b) => KEEP_SUBSETS.has(b.subset));

  chunks.push(`/* ${slug} — ${role} */`);

  const seen = new Set();
  for (const { subset, block } of blocks) {
    const family = field(block, 'font-family').replace(/['"]/g, '');
    const style = field(block, 'font-style') || 'normal';
    const weight = field(block, 'font-weight') || '400';
    const range = field(block, 'unicode-range');
    const urlMatch = block.match(/url\((https:[^)]+\.woff2)\)/);
    if (!urlMatch) continue;

    const wSlug = weight.replace(/\s+/g, '-');
    const name = `${slug}-${style}-${wSlug}-${subset}.woff2`;
    if (seen.has(name)) continue;
    seen.add(name);

    const buf = await get(urlMatch[1], true);
    writeFileSync(resolve(FONT_DIR, name), buf);
    total += buf.length;
    manifest.push({ family, file: name, bytes: buf.length });

    chunks.push(
      '@font-face {',
      `  font-family: '${family}';`,
      `  font-style: ${style};`,
      `  font-weight: ${weight};`,
      '  font-display: swap;',
      `  src: url('../assets/fonts/${name}') format('woff2');`,
      `  unicode-range: ${range};`,
      '}',
    );
  }
  chunks.push('');
}

writeFileSync(CSS_OUT, chunks.join('\n'));

console.log(`\n${manifest.length} files, ${(total / 1024).toFixed(1)} KB total`);
for (const m of manifest) console.log(`  ${m.file.padEnd(44)} ${(m.bytes / 1024).toFixed(1)} KB`);
console.log(`\nwrote ${CSS_OUT}`);
